# Change these first
owner: Dregos13 # Your GitHub organization or username, where this repository lives
repo: ClientStatus # The name of this repository

sites:

  # ACES CLIENT

  - name: ACES - Front
    url: https://$ACES_SITE_URL
  - name: Aces - Comments
    url: "https://$API_FTG_SITE_URL/comments"
    expectedStatusCodes:
      - 200
      - 401

  - name: Aces - Dashboards
    url: "https://$API_FTG_SITE_URL/dashboards"
    expectedStatusCodes:
      - 200
      - 401

  - name: Aces - Data-Logger
    url: "https://$API_FTG_SITE_URL/data-logger"
    expectedStatusCodes:
      - 200
      - 401

  - name: Aces - Data-Processing
    url: "https://$API_FTG_SITE_URL/data-processing"
    expectedStatusCodes:
      - 200
      - 401

  - name: Aces - Data-Sender
    url: "https://$API_FTG_SITE_URL/data-sender"
    expectedStatusCodes:
      - 200
      - 401

  - name: Aces - Hierarchy
    url: "https://$API_FTG_SITE_URL/hierarchy"
    expectedStatusCodes:
      - 200
      - 401

  - name: Aces - Instruments
    url: "https://$API_FTG_SITE_URL/instruments"
    expectedStatusCodes:
      - 200
      - 401

  - name: Aces - Layers
    url: "https://$API_FTG_SITE_URL/layers"
    expectedStatusCodes:
      - 200
      - 401

  - name: Aces - Notifications
    url: "https://$API_FTG_SITE_URL/notifications"
    expectedStatusCodes:
      - 200
      - 401

  #ALULA CLIENT

  - name: AlUla
    url: https://$ALULA_SITE_URL
  - name: AlUla - Comments
    url: "https://$API_ALULA_SITE_URL/comments"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Dashboards
    url: "https://$API_ALULA_SITE_URL/dashboards"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Data-Logger
    url: "https://$API_ALULA_SITE_URL/data-logger"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Data-Processing
    url: "https://$API_ALULA_SITE_URL/data-processing"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Data-Sender
    url: "https://$API_ALULA_SITE_URL/data-sender"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Hierarchy
    url: "https://$API_ALULA_SITE_URL/hierarchy"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Instruments
    url: "https://$API_ALULA_SITE_URL/instruments"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Layers
    url: "https://$API_ALULA_SITE_URL/layers"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Notifications
    url: "https://$API_ALULA_SITE_URL/notifications"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Instruments
    url: "https://$API_ALULA_SITE_URL/instruments"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Layers
    url: "https://$API_ALULA_SITE_URL/layers"
    expectedStatusCodes:
      - 200
      - 401
  - name: AlUla - Notifications
    url: "https://$API_ALULA_SITE_URL/notifications"
    expectedStatusCodes:
      - 200
      - 401
  - name: America
    url: https://$AMERICA_SITE_URL
  - name: Demo
    url: https://$DEMO_SITE_URL
  - name: DigitalDemo
    url: https://$DIGITALDEMO_SITE_URL
  - name: Erindia
    url: https://$ERINDIA_SITE_URL
  - name: Europe
    url: https://$EUROPE_SITE_URL
  - name: FTG
    url: https://$FTG_SITE_URL
  - name: Hattadam
    url: https://$HATTADAM_SITE_URL
  - name: MetroSantiago
    url: https://$METROSANTIAGO_SITE_URL
  - name: Neom
    url: https://$NEOM_SITE_URL
  - name: RGSUSA
    url: https://$RGSUSA_SITE_URL
  - name: RTA
    url: https://$RTA_SITE_URL
  - name: Sensonet
    url: https://$SENSONET_SITE_URL
  - name: Transalta
    url: https://$TRANSALTA_SITE_URL
  - name: Wang
    url: https://$WANG_SITE_URL
  - name: WapCos
    url: https://$WAPCOS_SITE_URL


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ramidregos.com
  # baseUrl: /your-repo-name
  logoUrl: https://status.ramidregos.com/proqio.svg
  theme: dark
  name: Proqio Monitoring
  # Optional: add a custom logo to the status page
  introTitle: "**Upptime** is the uptime monitor and status page, powered entirely by GitHub."
  introMessage: This Monitor tool will show the status of all Proqio clients.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
